# Generated by Django 3.1.7 on 2021-03-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sertificate', models.CharField(max_length=9)),
                ('certification_year', models.DateField()),
                ('pages', models.IntegerField()),
                ('pictures', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BooksSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=50)),
                ('transcript_number', models.CharField(max_length=9)),
                ('admission_year', models.DateField()),
                ('course', models.IntegerField()),
                ('special_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.special')),
            ],
        ),
        migrations.CreateModel(
            name='GiveBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=5)),
                ('course', models.IntegerField()),
                ('semestr', models.IntegerField()),
                ('special_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.special')),
            ],
        ),
        migrations.CreateModel(
            name='BooksStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.book')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.bookssection')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='special_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.special'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.teacher')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dot_app.book')),
            ],
        ),
    ]
