# Generated by Django 3.1.7 on 2021-03-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='special_id',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='booksstructure',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booksstructure',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='curriculum',
            old_name='special_id',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='givebook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='givebook',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='special_id',
            new_name='special',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department_id',
            new_name='department',
        ),
    ]
